version: '3.8'
services:
  flask-app:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - save_volume:/data
    ports:
      - "5000:5000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  save_volume: